subscription_id = "((subscription_name))"
tenant_id = "((tenant_name))"
resource_group_name = "((resource_group_name))"
location = "((region_name))"
cluster_name = "((cluster_name))"
kubernetes_version = "((required_K8s_version))"
system_node_count = "((node_pool_count))"
